services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      # ── HTTP / HTTPS-Entrypoints ───────────────────────────
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # 301-Redirect von http:// → https://
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true

      # ── ACME / Dashboard etc. (wie bisher) ─────────────────
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=m.buechner@dnb.de
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --api.dashboard=true
    labels:
      - traefik.enable=true
      # --- Middleware definieren ---
      - traefik.http.middlewares.hsts.headers.forceSTSHeader=true
      - traefik.http.middlewares.hsts.headers.stsSeconds=63072000
      - traefik.http.middlewares.hsts.headers.stsPreload=true
    ports: ['80:80', '443:443']
      # - "8080:8080"           # Traefik-Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt
    networks: [monitoring]
    restart: unless-stopped

  prometheus:
    image: bitnami/prometheus:3.4.1
    user: "1001"
    container_name: prometheus
    environment:
      - EXTRA_FLAGS=--storage.tsdb.retention.time=30d
    volumes:
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml:ro
      - ./prometheus/sd:/opt/bitnami/prometheus/conf/sd:ro
      - prometheus_data:/bitnami/prometheus
    # zum Debuggen
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.prom.rule=Host(`prometheus:9090`)
    #   - traefik.http.routers.prom.entrypoints=websecure
    #   - traefik.http.routers.prom.tls.certresolver=le
    # optional Basic Auth
    #   - traefik.http.routers.prom.middlewares=prom-auth
    #   - traefik.http.middlewares.prom-auth.basicauth.users=admin:$$apr1$$KVoe...   # htpasswd
    networks: [monitoring]
    ports: ['9090:9090']
    restart: unless-stopped

  blackbox:
    image: bitnami/blackbox-exporter:0.26.0
    user: "1001"
    container_name: blackbox
    environment:
      - EXTRA_FLAGS=--max-requests=20
    volumes:
      - ./blackbox/blackbox.yml:/opt/bitnami/blackbox-exporter/conf/blackbox.yml:ro
    networks: [monitoring]
    ports: ['9115:9115']
    restart: unless-stopped

  alertmanager:
    image: bitnami/alertmanager:0.28.1
    user: "1001"
    container_name: alertmanager
    environment:
      - EXTRA_FLAGS=--web.route-prefix=/alertmanager \
        --web.external-url=https://status.deutsche-digitale-bibliothek.de/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/opt/bitnami/alertmanager/conf/config.yml:ro
      - alertmanager_data:/opt/bitnami/alertmanager/data
    ports: ["9093:9093"]
    # zum Debuggen
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.am.rule=Host(`status.deutsche-digitale-bibliothek.de`) && PathPrefix(`/alertmanager`)
    #   - traefik.http.routers.am.entrypoints=websecure
    #   - traefik.http.routers.am.tls.certresolver=le
    networks: [monitoring]
    restart: unless-stopped

  grafana:
    image: bitnami/grafana:12.0.1
    user: "1001"
    container_name: grafana
    environment:
      # Anonyme Besucher dürfen nur LESEN
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer  # nur Dashboard‐Lesen :contentReference[oaicite:1]{index=1}
      # interne User melden sich normal an
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=heywesty-trafficlight-panel
      # Drittes Netz‐Schloss
      - GF_SECURITY_COOKIE_SECURE=true     # Cookies nur via HTTPS
      - GF_SECURITY_ALLOW_EMBEDDING=false  # verhindert Click-Jacking
    networks: [monitoring]
    ports: ['3000:3000']
    volumes:
      - grafana_data:/bitnami/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`status.deutsche-digitale-bibliothek.de`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=le
      - traefik.http.routers.grafana.middlewares=hsts
    depends_on: [prometheus]
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:
  traefik_data:

networks:
  monitoring: {}            # internes Netz für alle
